In [1]:
import pandas as pd
import numpy as np
import re
from tqdm import tqdm_notebook
from sklearn.metrics.pairwise import cosine_distances
from sklearn.metrics import jaccard_score

In [2]:
df_24 = pd.read_csv('./data/24.csv')
df_lenta = pd.read_csv('./data/lenta.csv')
df_vesti = pd.read_csv('./data/vesti.csv')


In [3]:
df_vesti.head()

Unnamed: 0        date                                               url  \
0           0  2019.05.19          https://www.vesti.ru/doc.html?id=3148761   
1           1  2019.05.19     https://eurovision.russia.tv/article/1208392/   
2           2  2019.05.19         https://www.vesti.ru/sdoc.html?id=3148470   
3           3  2019.05.19  https://russia.tv/article/show/article_id/66477/   
4           4  2019.05.19       https://www.vestifinance.ru/articles/119315   

                                               title  \
0            В Каире взорвался туристический автобус   
1  Результат не понизил, Россию не подвел: Лазаре...   
2  Маленькая дочь мешала личному счастью "мамы в ...   
3  Вышел первый трейлер многосерийной драмы "Зуле...   
4  Торговая война между США и Китаем вызывает отт...   

                                                text  
0  В числе пострадавших при взрыве рядом с турист...  
1   Выступление Сергея Лазарева на втором полуфин...  
2                                                     
3  Войти под логином RUSSIA.TVВосстановить пароль...  
4  Прямой ЭфирЗапрет Китая на импорт отходов ожив...

In [6]:
news_df = pd.concat([df_24, df_lenta, df_vesti], ignore_index=True)

In [7]:
print(news_df.shape)

news_df.head()


(8368, 5)


Unnamed: 0        date                                                url  \
0           0  2019/05/19  https://24smi.org/news/155521-film-irlandets-a...   
1           1  2019/05/19  https://24smi.org/news/155583-klip-postradavsh...   
2           2  2019/05/19  https://24smi.org/news/155579-patriarkh-kirill...   
3           3  2019/05/19  https://24smi.org/news/155572-na-mks-vpervye-i...   
4           4  2019/05/19  https://24smi.org/news/155569-deieneris-iz-igr...   

                                               title  \
0                    Фильм «Ирландец»: актеры и роли   
1  Клип пострадавшей в аварии певицы Максим сняли...   
2  Патриарх Кирилл сообщил, на сколько увеличится...   
3           На МКС впервые испытали летающих роботов   
4  Дейенерис из «Игры престолов» трогательно расп...   

                                                text  
0  Netflix представил фильм Мартина Скорсезе «Ирл...  
1  Представитель певицы Максим сообщила, что пока...  
2  Патриарх Московский и всея Руси Кирилл озвучил...  
3  На МКС прошли первые испытания оборудования дл...  
4  В честь показа финальной серии «Игры престолов...

In [13]:
test = news_df.text[0]

In [14]:
line = ' '.join(filter(lambda word: word != '', re.findall('[\w\d]*', test)))

In [8]:
news_df = news_df[news_df.text.notnull()]

In [9]:
from collections import defaultdict

In [10]:
news_df.shape

(8228, 5)

In [14]:
def clear_new(new):
    res = ''
    try:
        res = ' '.join(filter(lambda word: word != '', re.findall('[\w\d]*', new))).lower()
    except Exception as e:
        print(new)
    return res

In [15]:
texts_df = news_df.text.apply(clear_new)

In [16]:
texts_df.head()

0    netflix представил фильм мартина скорсезе ирла...
1    представитель певицы максим сообщила что пока ...
2    патриарх московский и всея руси кирилл озвучил...
3    на мкс прошли первые испытания оборудования дл...
4    в честь показа финальной серии игры престолов ...
Name: text, dtype: object

In [17]:
BOW = defaultdict(lambda: [], {})

for num, row in tqdm_notebook(enumerate(texts_df)):
    words = row.split()
    for i in range(1, len(words)):
        key = ' '.join([words[i - 1], words[i]])
        BOW[key].append(num)

In [18]:
arr = np.zeros((texts_df.shape[0], len(BOW)), dtype=np.uint8)

In [19]:
for num, shingle in enumerate(BOW):
    arr[BOW[shingle], num] = 1

In [27]:
BOW['дата выхода']

[0,
 22,
 25,
 98,
 107,
 126,
 168,
 168,
 172,
 228,
 229,
 289,
 290,
 355,
 412,
 456,
 475,
 489,
 510,
 511,
 603,
 644,
 660,
 684,
 705,
 707,
 847,
 874,
 892,
 892,
 914,
 920,
 953]

In [29]:
def

1

In [128]:
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for i in t:
    print(i.nonzero())

(array([0, 1, 2]),)
(array([0, 1, 2]),)
(array([0, 1, 2]),)


In [149]:
arr.shape

(8228, 729996)

In [133]:
vectors = []

for num, i in tqdm_notebook(enumerate(arr)):
    vectors.append(set(i.nonzero()[0]))
    



In [132]:
vectors[144]

(144,
 {188,
  200,
  1189,
  1444,
  1687,
  1970,
  2236,
  9583,
  10149,
  10401,
  10402,
  10404,
  10423,
  10544,
  11452,
  11462,
  11463,
  12748,
  12907,
  14084,
  14286,
  14287,
  18336,
  18861,
  18955,
  18966,
  18967,
  21342,
  21416,
  25856,
  25857,
  25858,
  25859,
  25860,
  25861,
  25862,
  25863,
  25864,
  25865,
  25866,
  25867,
  25868,
  25869,
  25870,
  25871,
  25872,
  25873,
  25874,
  25875,
  25876,
  25877,
  25878,
  25879,
  25880,
  25881,
  25882,
  25883,
  25884,
  25885,
  25886,
  25887,
  25888,
  25889,
  25890,
  25891,
  25892,
  25893,
  25894,
  25895,
  25896,
  25897,
  25898,
  25899,
  25900,
  25901,
  25902,
  25903,
  25904,
  25905,
  25906,
  25907,
  25908,
  25909,
  25910,
  25911,
  25912,
  25913,
  25914,
  25915,
  25916,
  25917,
  25918,
  25919,
  25920,
  25921,
  25922,
  25923,
  25924,
  25925,
  25926,
  25927,
  25928,
  25929,
  25930,
  25931,
  25932,
  25933,
  25934,
  25935,
  25936,
  25937,
  259

In [138]:
pairs = []

for i in tqdm_notebook(range(len(vectors))):
    max_ = 0
    max_index = 0
    for j in range(i + 1, len(vectors)):
        set1 = set(vectors[i])
        set2 = set(vectors[j])
        try:
            inter = len(set1.intersection(set2))
            union = len(set1.union(set2))
            jac = inter / union
        except ZeroDivisionError:
            continue
        if jac > max_:
            max_ = jac
            max_index = j
    
    pairs.append((i, max_index, jac))
    

In [154]:
pairs

[(0, 489, 0.0),
 (1, 822, 0.0),
 (2, 432, 0.0),
 (3, 547, 0.0),
 (4, 718, 0.0023584905660377358),
 (5, 2432, 0.0),
 (6, 316, 0.0),
 (7, 638, 0.0),
 (8, 1033, 0.0),
 (9, 294, 0.0029154518950437317),
 (10, 1100, 0.0),
 (11, 1021, 0.011764705882352941),
 (12, 294, 0.0),
 (13, 945, 0.0),
 (14, 405, 0.004310344827586207),
 (15, 43, 0.0),
 (16, 667, 0.0),
 (17, 20, 0.0),
 (18, 29, 0.0),
 (19, 2686, 0.004),
 (20, 5268, 0.0),
 (21, 241, 0.0),
 (22, 289, 0.0),
 (23, 507, 0.0),
 (24, 1262, 0.0),
 (25, 511, 0.0),
 (26, 84, 0.0),
 (27, 185, 0.0038314176245210726),
 (28, 46, 0.0),
 (29, 447, 0.0030864197530864196),
 (30, 338, 0.0),
 (31, 701, 0.0),
 (32, 900, 0.0),
 (33, 1075, 0.0),
 (34, 138, 0.0),
 (35, 763, 0.0),
 (36, 75, 0.0),
 (37, 57, 0.0),
 (38, 1285, 0.0),
 (39, 361, 0.004048582995951417),
 (40, 3337, 0.004166666666666667),
 (41, 56, 0.0),
 (42, 857, 0.0),
 (43, 162, 0.0),
 (44, 445, 0.0),
 (45, 49, 0.0),
 (46, 302, 0.008620689655172414),
 (47, 49, 0.0),
 (48, 516, 0.0),
 (49, 968, 0.0),
 

In [119]:
len(shigle_indexs[5365].intersection(shigle_indexs[5464])) / len(shigle_indexs[5365].union(shigle_indexs[5464]))

1.0

In [139]:
filtered_pairs = list(filter(lambda p: p[2] > 0, pairs))

In [141]:
max(filtered_pairs, key=lambda p: p[2])

(5365, 5464, 1.0)

In [143]:
vectors[5365]

{1687,
 2825,
 2858,
 2859,
 6336,
 9458,
 9459,
 12808,
 13748,
 15602,
 15868,
 19591,
 28720,
 30484,
 33646,
 40510,
 46727,
 47104,
 48607,
 59025,
 63399,
 68960,
 71596,
 80794,
 81988,
 150138,
 150139,
 151173,
 164704,
 178626,
 192927,
 215913,
 295707,
 301962,
 340776,
 342872,
 395101,
 445615,
 451538,
 487938,
 501937,
 593666,
 672120,
 720486,
 720487,
 726681,
 727581,
 728936,
 728937,
 728938,
 728939,
 728940,
 728941,
 728942,
 728943,
 728944,
 728945,
 728946,
 728947,
 728948,
 728949,
 728950,
 728951,
 728952,
 728953,
 728954,
 728955,
 728956,
 728957,
 728958,
 728959,
 728960,
 728961,
 728962,
 728963,
 728964,
 728965,
 728966,
 728967,
 728968,
 728969,
 728970,
 728971,
 728972,
 728973,
 728974,
 728975,
 728976,
 728977}

In [144]:
vectors[5464]

{1687,
 2825,
 2858,
 2859,
 6336,
 9458,
 9459,
 12808,
 13748,
 15602,
 15868,
 19591,
 28720,
 30484,
 33646,
 40510,
 46727,
 47104,
 48607,
 59025,
 63399,
 68960,
 71596,
 80794,
 81988,
 150138,
 150139,
 151173,
 164704,
 178626,
 192927,
 215913,
 295707,
 301962,
 340776,
 342872,
 395101,
 445615,
 451538,
 487938,
 501937,
 593666,
 672120,
 720486,
 720487,
 726681,
 727581,
 728936,
 728937,
 728938,
 728939,
 728940,
 728941,
 728942,
 728943,
 728944,
 728945,
 728946,
 728947,
 728948,
 728949,
 728950,
 728951,
 728952,
 728953,
 728954,
 728955,
 728956,
 728957,
 728958,
 728959,
 728960,
 728961,
 728962,
 728963,
 728964,
 728965,
 728966,
 728967,
 728968,
 728969,
 728970,
 728971,
 728972,
 728973,
 728974,
 728975,
 728976,
 728977}

In [146]:
list(BOW.keys())[1687]

'во время'

In [ ]:
list(BOW.keys())[1687]

True

In [159]:
(arr[5365] == arr[5464]).sum()

729996

In [160]:
arr.shape

(8228, 729996)